FROM node:22-alpine AS base

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

COPY . /app

WORKDIR ${FOLDER}

EXPOSE 5173
ENV PORT=5173
ENV HOSTNAME="0.0.0.0"
CMD ["npm", "run", "dev"]
